### APP levantada
GET http://localhost:3000/

### Documentación del API
GET http://localhost:3000/api-docs

#################
### Inmuebles ###
#################
### GET
GET http://localhost:3000/api/inmuebles

### POST
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso": "20",
    "letra": "D",
    "extension": "75",
    "habitaciones": "2",
    "alquilado": false,
    "propietario": " Mario Rodríguez",
    "email": "mario@unir.net"
}

### PUT
PUT http://localhost:3000/api/inmuebles/636aa57b2192e490f496f8ff
Content-Type: application/json

{
    "propietario": "Mariano Jiménez",
    "email": "mjifrias@gmail.com"
}

### DELETE
DELETE http://localhost:3000/api/inmuebles/636ad542718ba786e34fe183
